name: hexlet-project-ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup project
        run: make setup

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test

      - name: Linter
        run: make lint

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true